apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jk-2015-vagla
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: jk-2015-vagla
    spec:
      containers:

      - name: jk-2015-vagla
        image: eu.gcr.io/jawne-ksiegi/jk-2015-vagla:2
        args: ["--log-level", "debug"]
        env:
        - name: STATIC_URL
          value: https://storage.googleapis.com/eu.artifacts.jawne-ksiegi.appspot.com/django-static/eu.gcr.io/jawne-ksiegi/jk-2015-vagla:2/
        - name: SQLITE_DB
          value: /data/db.sqlite3
        volumeMounts:
        - name: jk-2015-vagla-data
          mountPath: /data

      volumes:

      - name: jk-2015-vagla-data
        gcePersistentDisk:
          pdName: jk-2015-vagla
          fsType: ext4

----

apiVersion: v1
kind: Service
metadata:
  name: jk-2015-vagla
spec:
  selector:
    run: jk-2015-vagla
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 146.148.7.14
