"""
Django settings for this project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "HERE GOES RANDOM STRING"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["finanse-kww.piotrwaglowski.pl"]


# Application definition

INSTALLED_APPS = (
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'pipeline',
	'kw',
)

MIDDLEWARE_CLASSES = (
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'vagla.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [os.path.join(BASE_DIR, "vagla", "templates")],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

STATICFILES_DIRS = [os.path.join(BASE_DIR, "vagla", "static")]

WSGI_APPLICATION = 'vagla.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.sqlite3',
		'NAME': os.getenv("SQLITE_DB", "./db.sqlite3"),
	}
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'pl-pl'

TIME_ZONE = 'Europe/Warsaw'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files

LIBCLOUD_PROVIDERS = {
	'gs': {
		'type': 'libcloud.storage.types.Provider.GOOGLE_STORAGE',
		'user': 'HERE GOES SOMETHING',
		'key': 'HERE GOES SOMETHING',
		'bucket': 'jk-2015-vagla',
		'base_url': 'https://storage.googleapis.com/jk-2015-vagla/',
	},
}

DEFAULT_FILE_STORAGE = 'djlibcloud.providers.gs'
MEDIA_URL = LIBCLOUD_PROVIDERS['gs']['base_url']

STATICFILES_FINDERS = (
	'django.contrib.staticfiles.finders.FileSystemFinder',
	'django.contrib.staticfiles.finders.AppDirectoriesFinder',
	'pipeline.finders.PipelineFinder',
)

PIPELINE = {
	'COMPILERS': ('pipeline.compilers.sass.SASSCompiler',),

	'STYLESHEETS': {
		'main': {
			'source_filenames': (
				'sass/style.sass',
			),
			'output_filename': 'css/main.css',
		},
	},
}

PIPELINE['CSS_COMPRESSOR'] = None
PIPELINE['SASS_BINARY'] = '/usr/bin/env sassc'

STATICFILES_STORAGE = 'pipeline.storage.PipelineStorage'
STATIC_ROOT = 'static'
STATIC_URL = os.getenv("STATIC_URL", "http://localhost:8000/")
