# Generated by Django 4.0 on 2022-12-01 09:13

from django.db import migrations, models
import django.db.models.deletion
import kw.models


class Migration(migrations.Migration):

	initial = True

	dependencies = [
	]

	operations = [
		migrations.CreateModel(
			name='Account',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('num_id', models.CharField(max_length=30, verbose_name='numeric id')),
				('name', models.CharField(max_length=200, verbose_name='name')),
			],
			options={
				'verbose_name': 'account',
				'verbose_name_plural': 'accounts',
				'ordering': ['num_id'],
			},
		),
		migrations.CreateModel(
			name='AccountRelationType',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('text_id', models.CharField(max_length=30, verbose_name='text id')),
			],
			options={
				'verbose_name': 'account relation type',
				'verbose_name_plural': 'account relation types',
			},
		),
		migrations.CreateModel(
			name='Document',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('date', models.DateField(null=True, verbose_name='date')),
				('date_posted', models.DateField(auto_now_add=True, verbose_name='date posted')),
				('issuer_name', models.CharField(max_length=100, verbose_name='issuer name')),
				('number', models.CharField(max_length=50, verbose_name='number')),
			],
			options={
				'verbose_name': 'document',
				'verbose_name_plural': 'documents',
				'ordering': ('issuer_name', 'number'),
			},
		),
		migrations.CreateModel(
			name='DocumentType',
			fields=[
				('id', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='id')),
				('name', models.CharField(max_length=30, verbose_name='name')),
			],
			options={
				'verbose_name': 'document type',
				'verbose_name_plural': 'document types',
			},
		),
		migrations.CreateModel(
			name='Turnover',
			fields=[
				('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='turnover', serialize=False, to='kw.account', verbose_name='account')),
				('debit', models.IntegerField(verbose_name='debit')),
				('credit', models.IntegerField(verbose_name='credit')),
				('debit_balance', models.IntegerField(verbose_name='debit balance')),
				('credit_balance', models.IntegerField(verbose_name='credit balance')),
			],
			options={
				'verbose_name': 'turnover',
				'verbose_name_plural': 'turnovers',
				'managed': False,
			},
		),
		migrations.CreateModel(
			name='BankTransfer',
			fields=[
				('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kw.document')),
				('amount', models.IntegerField(verbose_name='amount')),
				('title', models.CharField(max_length=200, verbose_name='title')),
			],
			options={
				'verbose_name': 'bank transfer',
				'verbose_name_plural': 'bank transfers',
			},
			bases=('kw.document',),
		),
		migrations.CreateModel(
			name='Invoice',
			fields=[
				('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kw.document')),
				('date_of_sale', models.DateField(verbose_name='date of sale')),
				('pit_amount', models.IntegerField(default=0, verbose_name='PIT amount')),
				('buyer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bought', to='kw.account', verbose_name='buyer')),
				('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold', to='kw.account', verbose_name='seller')),
			],
			options={
				'verbose_name': 'invoice',
				'verbose_name_plural': 'invoices',
			},
			bases=('kw.document',),
		),
		migrations.CreateModel(
			name='Event',
			fields=[
				('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
				('date', models.DateField(verbose_name='date')),
				('amount', models.IntegerField(verbose_name='amount')),
				('title', models.TextField(null=True)),
				('doc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='kw.document', verbose_name='document')),
				('dst', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='events_to', to='kw.account', verbose_name='to')),
				('src', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='events_from', to='kw.account', verbose_name='from')),
			],
			options={
				'verbose_name': 'event',
				'verbose_name_plural': 'events',
				'ordering': ('date', '-amount', 'title'),
			},
		),
		migrations.AddField(
			model_name='document',
			name='type',
			field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kw.documenttype', verbose_name='type'),
		),
		migrations.CreateModel(
			name='Attachment',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('name', models.CharField(max_length=100, verbose_name='name')),
				('file', models.FileField(upload_to=kw.models.upload_to, verbose_name='file')),
				('public', models.BooleanField(default=True, verbose_name='public')),
				('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='kw.document', verbose_name='document')),
			],
			options={
				'verbose_name': 'attachment',
				'verbose_name_plural': 'attachments',
			},
		),
		migrations.CreateModel(
			name='AccountRelation',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('dst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='kw.account', verbose_name='to')),
				('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='kw.account', verbose_name='from')),
				('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kw.accountrelationtype', verbose_name='type')),
			],
			options={
				'verbose_name': 'account relation',
				'verbose_name_plural': 'account relations',
			},
		),
		migrations.CreateModel(
			name='InvoiceLine',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('number', models.IntegerField(verbose_name='number')),
				('amount', models.IntegerField(verbose_name='amount')),
				('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kw.account', verbose_name='account')),
				('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='kw.invoice', verbose_name='invoice')),
			],
			options={
				'verbose_name': 'invoice line',
				'verbose_name_plural': 'invoice lines',
			},
		),
		migrations.AlterUniqueTogether(
			name='document',
			unique_together={('issuer_name', 'number')},
		),
		migrations.RunSQL(
"""CREATE VIEW kw_turnover_own AS
SELECT a.id, a.num_id, coalesce(debit, 0) as debit, coalesce(credit, 0) as credit, coalesce(debit, 0)-coalesce(credit, 0) as balance
FROM kw_account a
LEFT JOIN (
		SELECT k.id as acc, sum(dst.amount) as debit FROM kw_account k
		LEFT JOIN kw_event dst ON k.id = dst.dst_id AND dst.date < date()
		GROUP BY k.id) wn ON wn.acc = a.id
LEFT JOIN (
		SELECT k.id as acc, sum(src.amount) as credit FROM kw_account k
		LEFT JOIN kw_event src ON k.id = src.src_id AND src.date < date()
		GROUP BY k.id) ma ON ma.acc = a.id
ORDER BY id;"""),
		migrations.RunSQL(
"""CREATE VIEW kw_turnover AS
SELECT a.id, a.num_id, coalesce(sum(sub.debit), 0) as debit, coalesce(sum(sub.credit), 0) as credit, coalesce(sum(max(sub.balance, 0)), 0) as debit_balance, -coalesce(sum(min(sub.balance, 0)), 0) as credit_balance
FROM kw_account a
LEFT JOIN kw_turnover_own sub ON (sub.num_id = a.num_id OR sub.num_id LIKE a.num_id||'-%')
GROUP BY a.id
ORDER BY a.num_id;"""),
	]
