# Generated by Django 4.0 on 2022-12-01 09:13

from django.db import migrations, models
import django.db.models.deletion
import kw.models


class Migration(migrations.Migration):

	initial = True

	dependencies = [
	]

	operations = [
		migrations.CreateModel(
			name='Account',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('num_id', models.TextField()),
				('name', models.TextField()),
			],
			options={},
		),
		migrations.CreateModel(
			name='Document',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('date', models.DateField(null=True, verbose_name='date')),
				('date_posted', models.DateField(auto_now_add=True, verbose_name='date posted')),
				('issuer_name', models.CharField(max_length=100, verbose_name='issuer name')),
				('number', models.CharField(max_length=50, verbose_name='number')),
			],
			options={
				'verbose_name': 'document',
				'verbose_name_plural': 'documents',
				'ordering': ('issuer_name', 'number'),
			},
		),
		migrations.CreateModel(
			name='DocumentType',
			fields=[
				('id', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='id')),
				('name', models.CharField(max_length=30, verbose_name='name')),
			],
			options={
				'verbose_name': 'document type',
				'verbose_name_plural': 'document types',
			},
		),
		migrations.CreateModel(
			name='Event',
			fields=[
				('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
				('date', models.DateField(verbose_name='date')),
				('title', models.TextField(null=True)),
				('doc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='kw.document', verbose_name='document')),
				('dst', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='events_to', to='kw.account', verbose_name='to')),
				('src', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='events_from', to='kw.account', verbose_name='from')),
				('amount', models.IntegerField(verbose_name='amount')),
				('count', models.IntegerField(verbose_name='count', null=True)),
				('item_id', models.CharField(max_length=50)),
				('item_name', models.CharField(max_length=100)),
			],
			options={
				'verbose_name': 'event',
				'verbose_name_plural': 'events',
				'ordering': ('date', '-amount', 'title'),
			},
		),
		migrations.AddField(
			model_name='document',
			name='type',
			field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kw.documenttype', verbose_name='type'),
		),
		migrations.AlterUniqueTogether(
			name='document',
			unique_together={('issuer_name', 'number')},
		),
	]
