# Generated by Django 4.0 on 2022-10-13 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kw', '0002_views'),
    ]

    operations = [
		migrations.RunSQL(
			"DROP VIEW kw_turnover"
		),
		migrations.RunSQL(
			"DROP VIEW kw_event"
		),
		migrations.RunSQL(
			"DROP VIEW kw_event_all"
		),
		migrations.RunSQL(
			"DROP VIEW kw_event_banktransfer"
		),
		migrations.RunSQL(
			"DROP VIEW kw_event_banktransfer_matches"
		),
		migrations.RemoveField(
			model_name='banktransferruleevent',
			name='dst',
		),
		migrations.RemoveField(
			model_name='banktransferruleevent',
			name='dst_rel',
		),
		migrations.RemoveField(
			model_name='banktransferruleevent',
			name='rule',
		),
		migrations.RemoveField(
			model_name='banktransferruleevent',
			name='src',
		),
		migrations.RemoveField(
			model_name='banktransferruleevent',
			name='src_rel',
		),
		migrations.DeleteModel(
			name='BankTransferRule',
		),
		migrations.DeleteModel(
			name='BankTransferRuleEvent',
		),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
