# Generated by Django 4.0 on 2022-10-15 22:11

from django.db import migrations, models

from uuid import uuid4

class Migration(migrations.Migration):

    dependencies = [
        ('kw', '0006_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('issuer_name', 'number'), 'verbose_name': 'document', 'verbose_name_plural': 'documents'},
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='document',
            name='issuer_name',
            field=models.CharField(default=lambda: uuid4().hex, max_length=100, verbose_name='issuer name'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('issuer_name', 'number')},
        ),
        migrations.RemoveField(
            model_name='document',
            name='issuer',
        ),
    ]
