# Generated by Django 4.0 on 2022-10-15 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kw', '0008_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banktransfer',
            name='contractor',
        ),
    ]
