# Generated by Django 4.0 on 2022-10-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kw', '0009_drop_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
