# Generated by Django 4.0 on 2022-10-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kw', '0011_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateField(null=True, verbose_name='date'),
        ),
    ]
