# Generated by Django 4.0 on 2022-12-01 08:44

from django.db import migrations


class Migration(migrations.Migration):

	dependencies = [
		('kw', '0013_views'),
	]

	operations = [
		migrations.RunSQL("""DROP VIEW kw_turnover_own;"""),
		migrations.RunSQL("""DROP VIEW kw_turnover;"""),
		migrations.RemoveField(
			model_name='account',
			name='address',
		),
		migrations.RemoveField(
			model_name='account',
			name='address_public',
		),
		migrations.RemoveField(
			model_name='account',
			name='bank_account',
		),
		migrations.RemoveField(
			model_name='account',
			name='bank_account_public',
		),
		migrations.RemoveField(
			model_name='account',
			name='facebook_id',
		),
		migrations.RemoveField(
			model_name='account',
			name='facebook_public',
		),
		migrations.RemoveField(
			model_name='account',
			name='locality',
		),
		migrations.RemoveField(
			model_name='account',
			name='locality_public',
		),
		migrations.RemoveField(
			model_name='account',
			name='name_public',
		),
		migrations.RemoveField(
			model_name='account',
			name='shortcut',
		),
	]
